name: Publish container image

on:
  release:
    types: [published]

jobs:
  publish_to_registry:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_ORG: ibmcom
      DOCKERHUB_REPOSITORY: tutorial-application-log-analysis
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKERHUB_REPOSITORY }}
      
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
